In [3]:
print("The zero occurs at", 2*pi, "radians.")

ERROR: Error in print.default("The zero occurs at", 2 * pi, "radians."): invalid 'quote' argument

In [5]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [6]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [7]:
d = date()
cat("Today’s date is:", d, "\n" )

Today’s date is: Sat Oct 10 03:33:16 2026

In [9]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [10]:
cat(x, sep =" ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [11]:
cat("\n")

In [12]:
cat(x, sep=" / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [14]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [15]:
cat("The square root of",x,"is approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is approximately 2.65

In [16]:
evenno = c(2,4,6,8,10)
evenno

[1]  2  4  6  8 10

In [17]:
cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

In [18]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [19]:
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [20]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [21]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [23]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [24]:
paste("Everybody", "loves", "R Programming.", sep="*")

[1] "Everybody*loves*R Programming."

In [25]:
paste("Everybody", "loves", "R Programming.", sep="==")

[1] "Everybody==loves==R Programming."

In [26]:
names = c("Prof. Singh", "Mr. Venkat", "Dr.Jha")

In [27]:
names

[1] "Prof. Singh" "Mr. Venkat"  "Dr.Jha"

In [28]:
paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr.Jha is a good person."

In [29]:
paste(names, "is", "a good", "person.", collapse = ", and ")

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr.Jha is a good person."

In [30]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")

[1] "1# is first#2# is second#3# is third"

In [31]:
paste(1, " is first ", 2, " is second ", 3, " is third ", sep = "#")

[1] "1# is first #2# is second #3# is third "

In [32]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [33]:
x[1]

[1] "Ex_1"

In [34]:
x[2]

[1] "Ex_2"

In [35]:
x[3]

[1] "Ex_3"

In [36]:
x[5]

[1] "Ex_5"

In [37]:
x =  paste("Ex", 1:5, sep="_", collapse="")
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [38]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [40]:
x = paste("Ex", 1:5, sep="_", collapse = "")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [41]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [42]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [43]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [44]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [45]:
x = "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

In [46]:
x

[1] "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

In [47]:
strsplit(x, split="!")

[[1]]
[1] "The&"               "syntax&"            "of&"
[4] "paste&"             "is"                 "&available"
[7] "&inthe online-help"

In [48]:
x = "The&!syntax&!of&!paste&!is!&available!
&inthe online-help"

In [49]:
x

[1] "The&!syntax&!of&!paste&!is!&available!\n&inthe online-help"

In [51]:
strsplit(x, split = "&!")

[[1]]
[1] "The"                                "syntax"
[3] "of"                                 "paste"
[5] "is!&available!\n&inthe online-help"

In [53]:
y = strsplit(x, split = "!&")

In [54]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [55]:
y[[1]][2]

[1] "available!\n&inthe online-help"

In [56]:
 y[[1]][3]

[1] NA

In [57]:
dates = c("2020-07-24", "2021-08-25", "202209-26", "2023-10-27")

In [58]:
datesplt = strsplit(dates, "-")

In [59]:
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "202209" "26"

[[4]]
[1] "2023" "10"   "27"

In [61]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol=3, byrow=TRUE)

Warning message in matrix(unlist(datesplt), nrow = 4, ncol = 3, byrow = TRUE):
“data length [11] is not a sub-multiple or multiple of the number of rows [4]”

In [62]:
datemat

     [,1]   [,2] [,3]
[1,] 2020   07   24
[2,] 2021   08   25
[3,] 202209 26   2023
[4,] 10     27   2020

In [64]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol=3, byrow=TRUE)

Warning message in matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol = 3, byrow = TRUE):
“data length [11] is not a sub-multiple or multiple of the number of rows [4]”

In [65]:
datematrix

     [,1]   [,2] [,3]
[1,]   2020  7     24
[2,]   2021  8     25
[3,] 202209 26   2023
[4,]     10 27   2020

In [66]:
strsplit("Shalabh",split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [67]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
nchar(x)
nchar(y)

[1] 19

[1] 26

In [68]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
nzchar(x)
nzchar(y)

[1] TRUE

[1] TRUE

In [69]:
x = c("Apple", "Banana", "Cake")
x

[1] "Apple"  "Banana" "Cake"

In [70]:
nzchar(x)

[1] TRUE TRUE TRUE

In [71]:
y = c("Apple", "", "Cake")
y

[1] "Apple" ""      "Cake"

In [72]:
nzchar(y)

[1]  TRUE FALSE  TRUE

In [73]:
x = c("Apple", "Banana", "Cake")
nchar(x)

[1] 5 6 4

In [74]:
y = c(2, 4, 6)
nchar(y)

[1] 1 1 1

In [75]:
z = c(11, 222, 3333)
nchar(z)

[1] 2 3 4

In [76]:
z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 3 4 5

In [77]:
x = "R course will start from 24.07.2022"
toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [78]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"
tolower(z)

[1] "indian institute of technology"