## **Sequences**

In [1]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [2]:
10:1

 [1] 10  9  8  7  6  5  4  3  2  1

In [3]:
5:15

 [1]  5  6  7  8  9 10 11 12 13 14 15

In [4]:
15:5

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [5]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

In [6]:
-10:-1

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [7]:
-5:-15

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

In [8]:
-15:-5

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [9]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

In [10]:
1.23:10.54

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

In [11]:
10.54:2.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [12]:
-1.23:-10

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

In [13]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

In [14]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [15]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [16]:
x = 2
seq(1, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [17]:
x = 50
seq(0, x, x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [18]:
seq(1, 50, 1/2)

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [19]:
y = 2*x

In [20]:
y

[1] 100

In [21]:
x = c(9, 8, 7, 6)
ind = seq(along=x)
ind

[1] 1 2 3 4

In [22]:
x[ ind[2]]

[1] 8

In [23]:
Sys.time()

[1] "2026-09-03 06:32:05 UTC"

In [24]:
Sys.Date()

[1] "2026-09-03"

In [26]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [27]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [29]:
seq(as.Date("2017-01-01"), by = "months", length = 6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

In [30]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

In [32]:
start = as.Date("2016-1-1")
end = as.Date("2017-1-1")

out = seq(end, start, by = "-1 month")

out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

In [33]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [34]:
letters[1:3]

[1] "a" "b" "c"

In [35]:
letters[3:1]

[1] "c" "b" "a"

In [36]:
letters[21:23]

[1] "u" "v" "w"

In [37]:
letters[2]

[1] "b"

In [38]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [40]:
LETTERS[1:3]

[1] "A" "B" "C"

In [41]:
LETTERS[3:1]

[1] "C" "B" "A"

In [42]:
LETTERS[21:23]

[1] "U" "V" "W"

In [43]:
LETTERS[3]

[1] "C"

## **Repeats**

In [44]:
rep(3.5, times=10)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

In [45]:
rep(1:3, 4)

 [1] 1 2 3 1 2 3 1 2 3 1 2 3

In [47]:
x = 1.4
x

rep(x, times=3)

rep(x, each=3)

[1] 1.4

[1] 1.4 1.4 1.4

[1] 1.4 1.4 1.4

In [49]:
rep(3:5, each=5)

 [1] 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5

In [50]:
 rep(1:4, each = 2, times = 3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [51]:
rep(1:4, times = 3, each = 2)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [52]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [53]:
ans = seq(from=2, to=8, by=2)
ans

[1] 2 4 6 8

In [54]:
rep(1:4, ans)

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

In [55]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [56]:
rep(x, 3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [57]:
rep(c("a", "b", "c"), 2)

[1] "a" "b" "c" "a" "b" "c"

In [59]:
rep(c("apple", "banana", "cake"), 2)

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

In [60]:
rep(2, length.out=5)

[1] 2 2 2 2 2

In [61]:
rep(2, length=5)

[1] 2 2 2 2 2

In [62]:
rep(c(2,3), length=5)

[1] 2 3 2 3 2

In [63]:
rep(c(2,3,4), length=5)

[1] 2 3 4 2 3

In [64]:
rep("apple", length=5)

[1] "apple" "apple" "apple" "apple" "apple"

In [65]:
rep(c("a", "b", "c"), length=2)

[1] "a" "b"

In [66]:
rep(c("a", "b", "c"), length=5)

[1] "a" "b" "c" "a" "b"

## **Sorting**

In [68]:
y = c(8,5,7,6)
y

[1] 8 5 7 6

In [69]:
sort(y)

[1] 5 6 7 8

In [71]:
sort(y, decreasing=TRUE)

[1] 8 7 6 5

## **Ordering**

In [72]:
y = c(9,8,5,7,6)
y

[1] 9 8 5 7 6

In [73]:
order(y)

[1] 3 5 4 2 1

In [74]:
order(y, decreasing=TRUE)

[1] 1 2 4 5 3

## **Mode**

In [75]:
mode(2.1266)

[1] "numeric"

In [76]:
mode(c(2,22,55))

[1] "numeric"

In [77]:
mode("India")

[1] "character"

In [78]:
mode(c("India", "CANADA"))

[1] "character"

In [79]:
mode(factor(c("UP", "MP")) )

[1] "numeric"

In [80]:
mode(list("India", "USA"))

[1] "list"

In [81]:
mode(data.frame(x=1:2, y=c("India", "USA")))

[1] "list"

In [82]:
mode(print)

[1] "function"

## **Lists**

In [83]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [84]:
x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [85]:
x1+x2

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [86]:
x1[2,1] = "hello"
x1

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

In [87]:
x1+x2

ERROR: Error in x1 + x2: non-numeric argument to binary operator

In [89]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)
x1

x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [90]:
matlist = list(x1, x2)

In [91]:
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [93]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [94]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [95]:
z1 = list( c("water", "juice", "lemonade"),
rep(1:4, each=2), matrix(data=5:8, nrow=2,
ncol=2, byrow=T) )

z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [96]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [97]:
z1[1][2]

[[1]]
NULL

In [98]:
z1[[1]][2]

[1] "juice"